#----------------------------------------------------
#   ______     __         ______     __   __          |
#  /\  ___\   /\ \       /\  __ \   /\ "-.\ \         |
#  \ \ \____  \ \ \____  \ \  __ \  \ \ \-.  \        |
#   \ \_____\  \ \_____\  \ \_\ \_\  \ \_\\"\_\       |
#    \/_____/   \/_____/   \/_/\/_/   \/_/ \/_/       |
#                                                     |
#                 Created by Cerberus                 |
#-----------------------------------------------------|

#Elo
eloBase: 1000
eloK: 20

#Scoreboard prefix
setClanTagTabPrefix: false
flushScoreboardOnJoin: true

#Database settings
dbHost: 'localhost'
dbUser: 'clans'
dbPassword: 'password'
dbDb: 'clans'
dbPort: 3306

configVersion: 2